// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArchivedBadge: typeof import('./src/components/common/badge/archived-badge.vue')['default']
    BaseButton: typeof import('./src/components/common/buttons/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/common/card/base-card.vue')['default']
    LoadingIcon: typeof import('./src/components/common/buttons/LoadingIcon.vue')['default']
    Notification: typeof import('./src/components/common/NotificationPlugin/Notification.vue')['default']
    Notifications: typeof import('./src/components/common/NotificationPlugin/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBreadcrumbs: typeof import('./src/components/common/breadcrumbs/TheBreadcrumbs.vue')['default']
  }
}

export {}
